### ISSUE TITLE
Translate questions on list02_en directory

### ISSUE THREAD

**Issue by matheusvictor** [matheusvictor/Pydawan#35]
Questions in the [list02_en](https://github.com/matheusvictor/Pydawan/tree/master/list02_en) directory need to be translated into English.

**Comment by zard777** [comment]
Hello, I've done the translation for list02_en, please review #38 :)
____
Have a nice day

**Comment by matheusvictor** [comment]
#35

**Comment by matheusvictor** [comment]
@zard777 : I was surprised that your name does not appear in the list of contributors, so I reversed the last PR. Please send another one for me to accept. Thank you for understanding

**Comment by morenocl** [comment]
Hello, I take this work!

**Comment by zard777** [comment]
Hello @matheusvictor - somehow I cannot make PR from old branch `ad7dbc7` as last update from my Eng translation and yours, even you've reverted our merge. 

Well, I think you can accept PR from Chris for this issue (as #45 ) and close thread :+1:  
____________________
It's ok for me if I don't have a seat in the list of contributors, don't worry

**Comment by matheusvictor** [comment]
Closed at # 45

**Comment by matheusvictor** [comment]
@zard777 : Thank you for understanding!
