### ISSUE TITLE
Translate CONTRIBUTING.md

### ISSUE THREAD

**Issue by matheusvictor** [matheusvictor/Pydawan#36]

**Comment by nikznk** [comment]
Hi, I would like to do this one, should I add a new file called contributing-EN.md

**Comment by amusfq** [comment]
I would like to contribute to translating this project into Indonesian

**Comment by Wishnia** [comment]
I would love to translate this file into Polish.

**Comment by claire-lovisa** [comment]
Hi, I'd love to translate it to French !

**Comment by matheusvictor** [comment]
Thanks all for your contributions! :D
